### ISSUE TITLE
DatePicker组件重置value与显示隐藏问题

### ISSUE THREAD

**Issue by BoWang816** [ShuyunFF2E/cloud-react#111]
1、选择时间后，无法在外部重置value值，如点击重置按钮想改变value 值时无法改变;

2、打开时间选择框，但是选择时间未点确定后切换到其他页面，日历框没有隐藏掉，且在其他地方无法隐藏；

![20191226100026.jpg](https://i.loli.net/2019/12/26/uf4wm89xBd5srZn.jpg)
![20191226100038.jpg](https://i.loli.net/2019/12/26/hYNtmZLEiVGWyPq.jpg)

**Comment by silence717** [comment]
已修复，在v0.0.28版本发布
