### ISSUE TITLE
【Datepicker】minDate失效的问题 和 Datepicker浮层关闭的问题

### ISSUE THREAD

**Issue by heriky** [ShuyunFF2E/cloud-react#121]
***1. minDate的问题***
为Datepicker设置了minDate，小于minDate的日期仍然可以选择，minDate设置了2020-01-06但是仍然可以选择2019-12-31
![xxxxx.gif](https://i.loli.net/2020/01/06/MQfoEtKyw7RzxT5.gif)

2.***浮层的问题***
在modal中使用Datepicker，打开datepicker，然后直接关闭modal，这时候datepicker的浮层没有关闭。
![222.gif](https://i.loli.net/2020/01/06/5ZVsmr4bFHfdDLp.gif)

**Comment by silence717** [comment]
已修复，请升级版本到0.0.27验证
