### ISSUE TITLE
【！紧急！紧急！】Datepicker在初始化挂载的时候就会执行onChange事件

### ISSUE THREAD

**Issue by heriky** [ShuyunFF2E/cloud-react#126]
升级0.0.26版本后，Datepciker出现问题，会在挂载的时候就执行onChange事件。如果项目中onChange的事件处理中设置setState，那么会形成无限循环，页面和电脑双双卡死。

**Comment by silence717** [comment]
已修复，请升级版本到0.0.27验证

**Comment by heriky** [comment]
该问题又在0.0.29版本出现了，麻烦跟踪下。

**Comment by silence717** [comment]
已修复，请升级版本到0.0.30验证
