### ISSUE TITLE
[DatePicker] 三个问题详见下面

### ISSUE THREAD

**Issue by liyuan-meng** [ShuyunFF2E/cloud-react#169]
http://jira.yunat.com/browse/CROWD-1018

问题一：设置 defaultValue 和 hasClear={true}，初始时有时间图标，重新选择后图标消失
```javascript
<Datepicker hasClear={true} showToday={true} defaultValue={new Date('2020/2/10')} onChange={this.onInpChange} placeholder="年月日" />
```
期望：初使时有时间图标，重新选择后图标不消失

问题二：设置 minDate={new Date()}，比如今天13号，13号是可选的，我选择14号00时00分00秒，点击确定；然后再打开时间选择器，发现13号不能选了，需要设置时分秒之后13号才能选择。
```javascript
<Datepicker hasClear={true} minDate={new Date()} showTimePicker={true} showToday={true} defaultValue={new Date('2020/2/10')} onChange={this.onInpChange} placeholder="年月日" />
````
这个问题我觉得只要设置最小值是 new Date()，那么今天就应该一直是可选的，在选择了时分秒的时候，如果发现时分秒小于当前时分秒，这个时候确定按钮不可点击

问题三：样式问题。不可选时间和可选时间在同一个月份，同一行的不可选时间和可选时间没有对齐

**Comment by silence717** [comment]
已修复，麻烦在0.0.39中验证
