### ISSUE TITLE
【DatePicker】datepicker增加可设置间隔符的属性

### ISSUE THREAD

**Issue by BoWang816** [ShuyunFF2E/cloud-react#177]
应用场景：

目前回调中返回数据格式是2018/12/12；

- 如果后端需要的数据格式是2018-12-12，则需要业务中自己转换；
- 当使用年月组件时，如2018-12，没有直接的方法可以转换格式，则必须通过split先拆分，再进行字符串的拼接；

**Comment by seawind8888** [comment]
增加了format属性 format='YYYY-MM-DD'

**Comment by silence717** [comment]
请升级到0.0.44版本验证
