### ISSUE TITLE
[Field] setError或setErrors后,样式错误

### ISSUE THREAD

**Issue by greria** [ShuyunFF2E/cloud-react#194]
Field组件demos basic-forms

<img width="431" alt="图片" src="https://user-images.githubusercontent.com/16697576/75839712-6d02c680-5e04-11ea-8998-06bfbda8da65.png">

![图片](https://user-images.githubusercontent.com/16697576/75839747-86a40e00-5e04-11ea-8a69-655ae395dc60.png)

**Comment by silence717** [comment]
已修复，在0.0.47版本验证
