### ISSUE TITLE
[InputNumber] 手动输入与点击inputNumber右边的按钮获得的数据类型不统一

### ISSUE THREAD

**Issue by zhangruixue012** [ShuyunFF2E/cloud-react#230]
**描述一下问题**
1. InputNumber组件手动输入获取的值类型为字符串
2. 点击InputNumber旁边的上下箭头获取的值类型为数字
3. defaultValue设置为 '0', 输入框里未显示

**Comment by silence717** [comment]
0.0.51版本已修复，请升级验证。
