### ISSUE TITLE
[Tree] 问题汇总

### ISSUE THREAD

**Issue by liyuan-meng** [ShuyunFF2E/cloud-react#283]
1. 第一条数据的 children 长度为 0，树不渲染
2. 设置 maxLevel 的层级为4，刷新页面后，现有的第四层右键不可以新增，但是如果从第二层重新新增目录，可以一直新增下去，没有限制（CROWD-1424）
3. 删除目录的确认弹窗，不要显示图标（CROWD-1425）
4. 搜索树，点击放大镜没有进行搜索（CROWD-1434）
5. 本地模板左侧树，输入关键字检索，没有展开第三级目录(某些数据下偶现，可以在本地模板目录搜索a)（CROWD-1435）
6. 删除目录的回调函数，需要添加第二个参数，当前删除目录对象

**Comment by silence717** [comment]
升级到0.0.63版本进行验证
