### ISSUE TITLE
[Tree][TreeSelect] tree 组件行间距太大；treeSelect 中的选项会出现换行 

### ISSUE THREAD

**Issue by liyuan-meng** [ShuyunFF2E/cloud-react#491]
issue: CROWD-2062
Tree：行高过大，不美观
TreeS
elect：TreeSelect 会出现换行，不美观
![image](https://user-images.githubusercontent.com/34151318/90329229-5a0c3900-dfd5-11ea-92c7-68e6bef3b911.png)

**Comment by greria** [comment]
Tree组件下个版本中修复

**Comment by silence717** [comment]
tree的交互已全部修改，不存在此问题
