### ISSUE TITLE
[InputNumber] 组件回显最大、最小值会带上一位小数

### ISSUE THREAD

**Issue by runrunlolz** [ShuyunFF2E/cloud-react#534]
**如何复现**
---**描述一下问题**
清晰描述下当前 bug 的问题、现象。
InputNumber组件，输入超出最大或最小的限制时，回显的最大、最小值会带一位小数0

复现步骤：
```javascript
     <InputNumber defaultValue={1} min={1} max={100} precison={0} />
```

**期望的结果**
您期望的正确的应该是什么样子
回显正确精度的最大、最小值

**截图**
![image](https://user-images.githubusercontent.com/20176682/115669869-578b8b80-a37b-11eb-8800-8c1848a756ab.png)

如果可能，请贴一张截图。

**使用环境**

-   操作系统: [e.g. windows]
-   浏览器 [e.g. chrome, safari]
-   node 版本 [e.g. 10.0.0]
-   npm 版本[e.g. 6.4.1]

**Comment by baukh789** [comment]
fixed
