### ISSUE TITLE
ICON组件增加更多图标

### ISSUE THREAD

**Issue by BoWang816** [ShuyunFF2E/cloud-react#56]
需要增加以下图标

![image](https://user-images.githubusercontent.com/26587649/66810161-403b3900-ef61-11e9-9cdd-aaa23fb4e405.png)

![image](https://user-images.githubusercontent.com/26587649/66811020-edfb1780-ef62-11e9-8158-5a5a24e87e2b.png)

![image](https://user-images.githubusercontent.com/26587649/66983208-9edfee80-f0ea-11e9-8715-95f2ed95e079.png)

**Comment by silence717** [comment]
预览和隐藏已添加，在 cloud-react 的 0.0.11-0 版本中已更新，其余放在业务组件本身吧，目前使用场景不多。
