### ISSUE TITLE
DatePicker组件引用问题和弹出框的层级问题

### ISSUE THREAD

**Issue by heriky** [ShuyunFF2E/cloud-react#62]
1. 日期组件在demo中使用DatePicker的名字，但打包时自动生成的名字为Datepicker，通过cloud-react引入时，只能引入名为Datepicker的组件。
正确： `import { Datepicker } from 'cloud-react'`
错误： `import { DatePicker } from 'cloud-react'`

2. 点击日期组件时弹出的日历容器是挂在body上的，但是该容器没有层级z-index，但Modal组件的弹框容器是有比较大的z-index值，这会导致在Modal组件中使用日期组件时，日历被Modal覆盖。
日历容器不应该挂载在body上，因为无法判定使用者的z-index到底时多少。

**Comment by lazyperson** [comment]
挂在body下是最佳选择，因为挂在到某个DOM下可能会因为css样式问题导致日历组件被遮挡。可以通过 DatePicker组件提供的className来拓展DatePicker组件弹层的样式，在这个className里定义z-index 或者  稍后我可以给DatePicker组件增加z-index 对外属性。

**Comment by silence717** [comment]
在v0.0.26版本中修复，发布
